### ISSUE TITLE
Automatically create Cloud Map namespace if it doesn't exist

### ISSUE THREAD

**Issue by vanekjar** [aws/aws-cloud-map-mcs-controller-for-k8s#19]
When a `ServiceExport` is created for given service, controller attempts to create corresponding Cloud Map service record in an existing namespace with the same. In case the namespace is missing on the Cloud Map side, the reconciliation is not successful. 

**Task:** Create Cloud Map namespace on demand when it doesn't exist.

**Comment by thalleslmF** [comment]
hi @vanekjar can you assign me? i linked a pull request
