### ISSUE TITLE
Publishing not ready endpointslices to cloudmap

### ISSUE THREAD

**Issue by jagath25** [aws/aws-cloud-map-mcs-controller-for-k8s#192]
The current implementation syncs the not ready IPs also to cloud-map from the endpointslices. This ends up publishing not ready IPs to cloud-map. Can we make it a flag to push only healthy IPs to cloud-map?

**Comment by runakash** [comment]
We will have a look into this.

**Comment by runakash** [comment]
Fixed by https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s/pull/210
