### ISSUE TITLE
Improve endpoint reconciliation when importing services from Cloud Map 

### ISSUE THREAD

**Issue by vanekjar** [aws/aws-cloud-map-mcs-controller-for-k8s#21]
Current implementation always removes all existing endpoints and replaces them with a new `EndpointSlice`. Correct way would be to compute a diff and only add/remove endpoints that changed.

Similar implementation in K8s codebase
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpointslice/reconciler.go

**Comment by astaticvoid** [comment]
In fact, endpoint slice is never replaced, only created if none exists.
