### ISSUE TITLE
Support headless services

### ISSUE THREAD

**Issue by vanekjar** [aws/aws-cloud-map-mcs-controller-for-k8s#22]
Currently the controller supports only services of type ClusterIP, or in multi-cluster terms, ClusterSetIP ([see code](https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s/blob/1bb7568f7eade92fd01f59ec40de53948e1fdb64/pkg/controllers/cloudmap_controller.go#L246)).That's not fully compliant with the [MCS API](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#service-types). 

* Implement headless Services on the export side — headless Services is marked by a custom instance attribute
* Implement headless ServiceImports — import controller translates headless instances to Headless ServiceImport type
* Figure out corner case like — service with the same name is defined as headless in one cluster, but ClusterIP in another cluster

**Comment by fredjywang** [comment]
Closed as headless services is now supported by controller.
