### ISSUE TITLE
Connection Disruption During Rollout Restart 

### ISSUE THREAD

**Issue by yu-jianshu** [aws/aws-cloud-map-mcs-controller-for-k8s#270]
Hello, 

We exported service A from cluster A and import it to cluster B for pod B to call service A.
When we do `rollout restart` for deployment A, pod B will encounter failed TCP connection issues to call service A, even though `rollout restart` shouldn't affect the availability of service A. The disruption will recover after a short while.

We noticed there are endpoints registering/de-registering operations from cloud-map-mcs-controller-manager during the restart, and we don't have Health check configured in cloud map, so some traffic may send to the old endpoints before it get de-registered, will it be the cause of connection disruption? 

If yes, may I know if cloud-map-mcs-controller-for-k8s supports configuration of Health check? If no, can we request for this feature?

Thanks in advance and your answers will be much appreciated!

**Comment by WJay-tec** [comment]
Created a new issue that might help to fix this , https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s/issues/272

**Comment by runakash** [comment]
Going to close this in favor of #272
