### ISSUE TITLE
Utilising Endpoints instead of EndpointSlices

### ISSUE THREAD

**Issue by WJay-tec** [aws/aws-cloud-map-mcs-controller-for-k8s#272]
Based on my current observation and the problem encountered in this issue #270 , i realise the current implementation of the MCS controller obtains the `EndpointSlices` object instead of the `Endpoints` object when it comes to updating the cloud map with ip's of running pod.

This will cause issues related to RollingUpdate, as `EndpointSlices` is updated with newly created pod's ip even though the service have not passed its ReadinessProbe check. This should be mitigated if we instead take the info from `Endpoints` object instead, which only adds the pod's ip if it passes the readiness check.

**Comment by runakash** [comment]
> This will cause issues related to RollingUpdate, as EndpointSlices is updated with newly created pod's ip even though the service have not passed its ReadinessProbe check.

This is quite interesting. Is this documented behavior?

The Ready condition in `EndpointSlice` maps to [Pod's ready](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ready).

**Comment by WJay-tec** [comment]
Ah i see, then is the code checking the condition before updating cloud map? From what i see the unready ip was already updated in all the clusters before the pod was up. I could be wrong
