### ISSUE TITLE
Error - unable to retrieve ClusterId and ClusterSetId

### ISSUE THREAD

**Issue by gaussye** [aws/aws-cloud-map-mcs-controller-for-k8s#315]
I followed the guide to install all components. Why i got the following error messages? Could you please help?
{"level":"error","ts":1717482045.7828882,"logger":"controllers.CloudmapReconciler","msg":"Cloud Map reconciliation error","error":"ClusterProperty not found: ClusterId: , ClusterSetId: ","stacktrace":"github.com/aws/aws-cloud-map-mcs-controller-for-k8s/pkg/controllers/multicluster.(*CloudMapReconciler).Start\n\t/workspace/pkg/controllers/multicluster/cloudmap_controller.go:45\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/runnable_group.go:219"}
{"level":"error","ts":1717482047.7825332,"logger":"controllers.CloudmapReconciler","msg":"unable to retrieve ClusterId and ClusterSetId","error":"ClusterProperty not found: ClusterId: , ClusterSetId: ","stacktrace":"github.com/aws/aws-cloud-map-mcs-controller-for-k8s/pkg/controllers/multicluster.(*CloudMapReconciler).Reconcile\n\t/workspace/pkg/controllers/multicluster/cloudmap_controller.go:60\ngithub.com/aws/aws-cloud-map-mcs-controller-for-k8s/pkg/controllers/multicluster.(*CloudMapReconciler).Start\n\t/workspace/pkg/controllers/multicluster/cloudmap_controller.go:43\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sig^C
my-admin:~/environment/gate.io $ ^C

**Comment by runakash** [comment]
It says in the error message `ClusterProperty not found: ClusterId`. You have to get create this kind https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s?tab=readme-ov-file#usage
