### ISSUE TITLE
Support same service running in multiple clusters (Cluster ID)

### ISSUE THREAD

**Issue by vanekjar** [aws/aws-cloud-map-mcs-controller-for-k8s#47]
Current implementation assumes that `[namespace name, service name]` pair uniquely identifies a running service in a given cluster set. In case a service with the same name is exported from multiple clusters it causes conflict on the Cloud Map side (only one cluster can claim ownership over the Cloud Map service).

The goal is to enable the use case of the same service running across multiple clusters. Proposed solution:

* Cloud Map instances must be identified by some form of `cluster ID`. That way the controller can claim ownership over individual endpoints and not the whole service.
* Consider adopting existing [Cluster ID proposal](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/2149-clusterid) to uniquely identify clusters

**Comment by matthewgoodman13** [comment]
Resolved with #179
