### ISSUE TITLE
AWS SDK region is not correctly set

### ISSUE THREAD

**Issue by vanekjar** [aws/aws-cloud-map-mcs-controller-for-k8s#55]
Controller loads the target region from `AWS_REGION` env variable, but this variable is never set in configuration files. 

https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s/blob/ba9b31ca87969c5bd4e3cdf6259551c9216e36ad/main.go#L90

Error message when running the controller:

> 2021-10-19T23:07:39.211Z        ERROR   controllers.ServiceExport       error when creating new service in Cloud Map    {"serviceexport": "demo/demo-service", "namespace": "demo", "name": "demo-service", "error": "operation error ServiceDiscovery: ListNamespaces, failed to resolve service endpoint, an AWS region is required, but was not found"}

**Comment by cameronsenese** [comment]
Hi team,

I have encountered this issue when exporting a service.
Is there a workaround when using v0.1.0? (I.e. manually provide AWS region when exporting service?)

Regards..

**Comment by runakash** [comment]
Hey @cameronsenese 

We are working on this issue. The current workaround is to hardcode the region as env variable in [manager.yaml](https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s/blob/main/config/manager/manager.yaml#L54) like below

```
        env:
          - name: AWS_REGION
            value: us-west-2
```

And build the controller docker `make docker-build IMG=controller:0.1.0`

**Comment by cameronsenese** [comment]
Hey @runakash 

Thank you for the workaround - was able to get past this issue 👍
I think I found another problem (with Cloud Map service creation - will create a separate issue).

Regards..
